return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "nvim-treesitter/playground",
    "nvim-treesitter/nvim-treesitter-refactor",
  },
  opts = {
    refactor = {
      highlight_definitions = {
        enable = true,
        clear_on_cursor_move = true,
      },
      highlight_current_scope = {
        enable = true,
      },
      smart_rename = {
        enable = true,
        keymaps = {
          smart_rename = "grr",
        },
      },
      navigation = {
        enable = true,
        keymaps = {
          goto_definition = "gnd",
          list_definitions = "gnD",
          list_definitions_toc = "gO",
          goto_next_usage = "<a-*>",
          goto_previous_usage = "<a-#>",
        },
      },
    },
    ensure_installed = {
      "bash",
      "bitbake",
      "c",
      "cmake",
      "cpp",
      "css",
      "devicetree",
      "diff",
      "dockerfile",
      "gitcommit",
      "git_config",
      "gitignore",
      "git_rebase",
      "go",
      "groovy",
      "hocon",
      "html",
      "ini",
      "javascript",
      "jq",
      "json",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "ninja",
      "python",
      "query",
      "regex",
      "sql",
      "tsx",
      "typescript",
      "vim",
      "xml",
      "yaml",
    },
  },
}
