return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "nvim-treesitter/playground",
  },
  opts = {
    ensure_installed = {
      "bash",
      "bitbake",
      "c",
      "cmake",
      "cpp",
      "css",
      "devicetree",
      "diff",
      "dockerfile",
      "gitcommit",
      "git_config",
      "gitignore",
      "git_rebase",
      "go",
      "groovy",
      "hcl",
      "hocon",
      "html",
      "ini",
      "javascript",
      "jq",
      "json",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "ninja",
      "puppet",
      "python",
      "query",
      "regex",
      "sql",
      "terraform",
      "tsx",
      "typescript",
      "vim",
      "xml",
      "yaml",
    },
  },
}
